import Head from "next/head";
import Banner from "@/components/banner/banner";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Nextflix</h1>
      {/* <NavBar/> */}
      <Banner title="Clifford the red Dog" subTitle="A red dog who is a big softy" imageUrl="/static/clifford.webp"/>
      {/* <NetflixCards/> */}
    </>
  );
}
